name: phytosvit
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  sqflite: ^2.4.0
  path: ^1.9.1
  http: ^1.2.2
  flutter_native_splash: ^2.4.2
  connectivity_plus: ^6.1.0
  json_annotation: ^4.9.0
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  permission_handler: ^10.0.0
  ai_barcode_scanner: ^6.0.1
  camera: ^0.11.0+2
  table_calendar: ^3.1.2

dependency_overrides:
  path: ^1.9.1
  image: ^4.2.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter_native_splash:
  color: "#f6f8fa"
  image: assets/app_logo_ico.png
  android: false
  ios: true
  fullscreen: true
  android_12:
    image: assets/app_logo_ico.png
    icon_background_color: "#f6f8fa"
    android_gravity: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/app_logo_ico.png
    - assets/icon/app_icon.png
    - .env
  fonts:
    - family: RobotoFont
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
  generate: true

flutter_intl:
  enabled: true
